version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 1000
      runas: root